# EC Notebook for Lecture 9: Grouping Data in Pandas

This extra credit Python notebook will let you practice the material you saw in lecture.  Completing all parts of this notebook will earn +1 extra credit point to your grade in STAT 107! :)

This notebook is worth +1 if turned in before 11:30am on **Wednesday, Sept. 18** *(30 minutes before the next STAT 107 lecture)*.  You can feel free to complete it anytime for extra practice.

## 1. Importing pandas and reading data
For this notebook, we will use the Illinois GPA Distribution dataset -- as we did in lecture -- to answer a few questions on working with columns.

You can access the "GPA" dataset here: https://github.com/wadefagen/datasets/tree/master/gpa

In [18]:
import pandas as pd
df = pd.read_csv("gpa.csv")
df_course = df[(df["Subject"] == "CS") | (df["Subject"] == "STAT")]
df_lowlevel = df_course[df_course["Number"] < 400]
df_highlevel = df_course[df_course["Number"] >= 400]
df_highlevel

,Year,Term,YearTerm,Subject,Number,Course Title,A+,A,A-,B+,...,B-,C+,C,C-,D+,D,D-,F,W,Primary Instructor
836,2018,Fall,2018-fa,CS,410,Text Information Systems,133,37,16,3,...,1,0,0,0,0,0,0,0,1,"Zhai, Chengxiang"
837,2018,Fall,2018-fa,CS,411,Database Systems,63,25,43,26,...,5,3,2,3,3,1,0,0,2,"Alawini, Abdussalam A"
838,2018,Fall,2018-fa,CS,412,Introduction to Data Mining,18,54,34,12,...,9,8,5,2,0,0,0,0,0,"Li, Qi"
839,2018,Fall,2018-fa,CS,418,Interactive Computer Graphics,25,25,17,8,...,8,2,3,1,0,0,0,4,0,"Hart, John C"
840,2018,Fall,2018-fa,CS,419,Production Computer Graphics,5,15,7,2,...,0,1,0,0,0,0,0,0,0,"Shaffer, Eric G"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46424,2010,Summer,2010-su,CS,421,Progrmg Languages & Compilers,2,5,5,4,...,1,0,1,4,0,4,0,0,1,"Hafiz, Munawar"
46425,2010,Summer,2010-su,CS,598,Object-Oriented Prog & Design,3,22,0,0,...,0,0,0,0,0,0,0,0,0,"Johnson, Ralph E"
46539,2010,Summer,2010-su,STAT,400,Statistics and Probability I,4,15,7,2,...,4,1,2,2,0,1,0,3,1,"Monrad, Ditlev"
46540,2010,Summer,2010-su,STAT,410,Statistics and Probability II,5,10,2,2,...,1,0,1,3,0,0,0,2,1,"Stepanov, Alexei G"
46541,2010,Summer,2010-su,STAT,440,Statistical Data Management,4,12,8,1,...,0,0,0,0,0,0,0,0,0,"Unger, David"

## 2. Review: Boolean Logic and Conditionals
The Illinois CS and STAT Students Centers want to calculate the number of students who did an excellent job in the courses of CS and STAT. In this case, they define those who got an "A+" or "A" are excellent. Also, considering the course difficulty, they think those who got an "A-" in advanced-level courses (course level >= 400) should be counted in excellent students. Can you help them to get the number?

### Question 1: 
Using the GPA dataset, calculate the number of students who got "A+" or "A" (in all level CS and STAT courses) or "A-" (only in advanced-level CS and STAT courses) in the DataFrame `df`.

In [27]:
lowlevelexcellent = df_lowlevel["A+"].sum() + df_lowlevel["A"].sum()
highlevelexcellent = df_highlevel["A+"].sum() + df_highlevel["A"].sum() + df_highlevel["A-"].sum()
num_excellent_students = lowlevelexcellent + highlevelexcellent
print(num_excellent_students)

87191

In [28]:
## == TEST CASES for Question 2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(num_excellent_students == 87191), "The number does not appear correct."

## 3. Review: Adding a New Variable (column)
Thanks to your great job, CS and STAT Students Centers know better about their courses. And they recommend you to other departments' students center, so they're all coming to ask you for a favor. This time they are curious about the percentage of students who got "F" in each course.

### Question 2: 
Using the GPA dataset, calculate the number of students who got "F" of each course and add a new column titled `F rate`. To test your correctness, print the average `F rate` of all the courses.

In [42]:
df['F rate'] = df["F"] / (df["A+"] + df["A"] + df["A-"] + df["B+"] + df["B"] + df["B-"] +df["C+"] +df["C"] +df["C-"] + df["D+"] +df["D"] +df["D-"] +df["F"])
avg_f_rate = df["F rate"].mean()
avg_f_rate

0.01756480342663667

In [43]:
## == TEST CASES for Question 2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert(abs(avg_f_rate - 0.017564803426637177) < 0.01), "The rate does not appear correct."